content=["<dl>",
"<dt><a href='#Section0'>Pyelonephritis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Fever, nausea, and vomiting. On physical examination, flank tenderness is considered pathognomonic for pyelonephritis.",
"<br><strong>Test:</strong> Elevated WBC, and positive blood cultures.</p>",
"</dd>",
"<dt><a href='#Section1'>Vaginitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Significant pruritus or vaginal discharge.",
"<br><strong>Test:</strong> Positive potassium hydroxide (KOH) prep/wet mount and elevated vaginal pH.</p>",
"</dd>",
"<dt><a href='#Section2'>Interstitial cystitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Failure to respond to antibiotics.",
"<br><strong>Test:</strong> Negative urine cultures.</p>",
"</dd>",
"<dt><a href='#Section3'>Chlamydia urethritis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> None.",
"<br><strong>Test:</strong> Negative urine culture, positive polymerase chain reaction (PCR) test for Chlamydia.</p>",
"</dd>",
"</dl>"].join("\n");    