content=["<dl>",
"<dt><a href='#Section0'>Oesophagitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> None.",
"<br><strong>Test:</strong> Upper GI endoscopy with biopsy will show no Barrett's oesophagus findings on biopsy.</p>",
"</dd>",
"<dt><a href='#Section1'>GORD</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> None.",
"<br><strong>Test:</strong> Upper GI endoscopy with biopsy will show no Barrett's oesophagus findings on biopsy.</p>",
"</dd>",
"<dt><a href='#Section2'>Oesophageal adenocarcinoma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> May have none, or may have constitutional signs such as involuntary weight loss, low energy, and lymphadenopathy.",
"<br><strong>Test:</strong> Biopsy reveals adenocarcinoma.</p>",
"</dd>",
"<dt><a href='#Section3'>Gastritis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patient may have a hx of chronic NSAID use.Mild epigastric tenderness common.",
"<br><strong>Test:</strong> Upper GI endoscopy with biopsy will show no Barrett's oesophagus findings on biopsy.</p>",
"</dd>",
"</dl>"].join("\n");