content=["<dl>",
"<dt><a href='#Section0'>Mycoplasma pneumoniae pneumonia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Cannot be differentiated clinically or by routine laboratory tests. Co-infections with M pneumoniae, Chlamydia pneumoniae, and other bacteria are not uncommon. [13]  [14]",
"<br><strong>Test:</strong> Demonstration of seroconversion in paired sera, presence of anti-M pneumoniae IgM antibody in children aged 10 or under (several FDA-approved tests are available), demonstration of presence of M pneumoniae by culture and/or PCR.</p>",
"</dd>",
"<dt><a href='#Section1'>Pneumonia, bacterial</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients with pneumococcal pneumonia may be more ill, and are more likely to have comorbidities, but presentations overlap significantly. [13]  [14]",
"<br><strong>Test:</strong> Positive culture for Streptococcus pneumoniae or other bacteria in sputum, blood, and/or pleural fluid.</p>",
"</dd>",
"<dt><a href='#Section2'>Viral pneumonia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Similar presentation with wheezing present.",
"<br><strong>Test:</strong> Chest x-ray unlikely to show consolidation or pleural effusions.</p>",
"</dd>",
"</dl>"].join("\n");