content=["<dl>",
"<dt><a href='#Section0'>chronic suppurative otitis media</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> On otoscopy there is perforation of the pars tensa but no evidence of cholesteatoma.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section1'>otitis externa</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> On otoscopy there is swelling of the external canal and a scant discharge. The tympanic membrane is not visible or, if visible, appears inflamed, but no evidence of cholesteatoma.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section2'>benign necrotising otitis externa</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> The patient reports severe otalgia; a history of diabetes or other immunosuppression.On otoscopy there are granulations in the ear canal but no evidence of cholesteatoma.",
"<br><strong>Test:</strong> CT scan demonstrates soft tissue swelling of the ear canal with or without erosion of the petrous temporal bone.</p>",
"</dd>",
"<dt><a href='#Section3'>myringitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> On otoscopy there is inflammation of the tympanic membrane with or without granulations, but no evidence of cholesteatoma.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"</dl>"].join("\n");