content=["<dl>",
"<dt><a href='#Section0'>Non-compressive myelopathy</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Similar neurological picture. No history of trauma or other acute event.",
"<br><strong>Test:</strong> MRI confirms the lack of spinal cord compression or trauma.</p>",
"</dd>",
"<dt><a href='#Section1'>Transverse myelitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Signs of a unilateral involvement, incomplete lesion, or a Brown-Sequard's type of lesion.",
"<br><strong>Test:</strong> Lumbar puncture demonstrates increased WBC count and absence of infection.Spinal cord MRI reveals a cord lesion that enhances after gadolinium administration.</p>",
"</dd>",
"</dl>"].join("\n");