content=["<dl>",
"<dt><a href='#Section0'>Infectious mononucleosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> The clinical presentation of infectious mononucleosis syndrome is most commonly caused by Epstein-Barr virus (EBV) infection, and is clinically indistinguishable from CMV.",
"<br><strong>Test:</strong> EBV PCR assay; EBV serology</p>",
"</dd>",
"<dt><a href='#Section1'>HIV</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Acute HIV seroconversion often manifests with a febrile syndrome that may be difficult to distinguish from primary CMV disease.This syndrome may include fever, chills, and generalised lymphadenopathy.",
"<br><strong>Test:</strong> HIV serology; HIV RNA level</p>",
"</dd>",
"<dt><a href='#Section2'>Human herpes virus (HHV)-6</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> HHV-6 infection after transplantation may manifest in a clinically similar way to CMV disease, and can be distinguished only by the detection of HHV-6-specific antigens or nucleic acid in clinical specimens.",
"<br><strong>Test:</strong> HHV-6 PCR assay</p>",
"</dd>",
"<dt><a href='#Section3'>Other viral illness</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Viral infections often present as fever in immunocompromised patients and thus may be indistinguishable from CMV.",
"<br><strong>Test:</strong> Virus-specific culture and PCR assays</p>",
"</dd>",
"</dl>"].join("\n");