content=["<dl>",
"<dt><a href='#Section0'>Isolated hypotonia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Hypotonia during infancy but no associated dysmorphic features or congenital defects.",
"<br><strong>Test:</strong> Normal karyotype.</p>",
"</dd>",
"<dt><a href='#Section1'>Zellweger's syndrome</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Peroxisomal disorder with hypotonia, flat occiput and face, epicanthal folds, Brushfield spots, cataracts, single palmar crease, seizures.Difficult to distinguish clinically.",
"<br><strong>Test:</strong> Elevated very long chain fatty acids in plasma.Normal karyotype.</p>",
"</dd>",
"</dl>"].join("\n");