content=["<dl>",
"<dt><a href='#Section0'>Trigger finger</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> The finger can be fully extended with a notable click.",
"<br><strong>Test:</strong> Ultrasound: thickening and hypoechogenicity, with possible increased vascularity of the A1 pulley.</p>",
"</dd>",
"<dt><a href='#Section1'>Epithelioid sarcoma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Tends to be progressive and extend beyond localised digits.",
"<br><strong>Test:</strong> Biopsy: results can be difficult to determine but are often seen as well-defined eosinophilic cytoplasms and one or more atypical, eccentrically located nuclei, resulting in a plasmacytoid appearance.</p>",
"</dd>",
"<dt><a href='#Section2'>Camptodactyly</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Presence of little finger contracture from an early age.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section3'>Traumatic finger contracture</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> History of significant preceding trauma leading to injury of the proximal interphalangeal joint.",
"<br><strong>Test:</strong> X-ray of hand may show associated fracture.</p>",
"</dd>",
"</dl>"].join("\n");