content=["<dl>",
"<dt><a href='#Section0'>Micropenis due to another cause</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Isolated micropenis suggests inadequate testosterone production in the third trimester of gestation only.Most are due to hypogonadotropic hypogonadism (patients present with delayed puberty and no ambiguity of the genitals), growth hormone deficiency (short stature, poor growth), or as a part of a genetic syndrome (e.g., Prader-Willi syndrome).Patients typically have normal testes palpable, no hypospadias, and a normal 46,XY karyotype.",
"<br><strong>Test:</strong> Clinical diagnosis.No hormonal testing required if an isolated abnormality.</p>",
"</dd>",
"<dt><a href='#Section1'>Unilateral undescended testes (cryptorchidism)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients with isolated unilateral undescended testes have no micropenis, no hypospadias, and a normal 46,XY karyotype.Extremely common in normal boys, especially preterm infants.Bilateral abdominal testes are not common and further evaluation is indicated.",
"<br><strong>Test:</strong> Clinical diagnosis.Ultrasound abdomen/pelvis may be used to locate the testes.No further hormonal evaluation is indicated if this is an isolated finding.</p>",
"</dd>",
"</dl>"].join("\n");