content=["<dl>",
"<dt><a href='#Section0'>Hypertrophic scar</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> No association with skin type.Always preceded by injury.On physical examination there is evidence of contraction or contractures. View imageView image",
"<br><strong>Test:</strong> Diagnosis is clinical.Immunohistochemistry demonstrates flatter, less distinct bundles of fibres, presence of myofibroblasts, and increased density of blood vessels and cells.</p>",
"</dd>",
"<dt><a href='#Section1'>Dermatofibroma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Usually no precipitating trauma but similar slow growth.Clinically, may appear as raised skin nodule, but may have subdermal extension.",
"<br><strong>Test:</strong> Skin biopsy demonstrates proliferation of fibroblasts and dermal fibrosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Dermatofibrosarcoma protuberans</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Clinically, the skin can appear to be normal on inspection, but is contiguous with a palpable tumor that arises from the dermis and spreads into the underlying tissue.",
"<br><strong>Test:</strong> Diagnosis may be difficult, and when in doubt histological examination is necessary. This demonstrates neoplastic spindle-shaped nuclei.An incisional biopsy with a large sample is required.</p>",
"</dd>",
"</dl>"].join("\n");