content=["<dl>",
"<dt><a href='#Section0'>Bacterial pneumonia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating features in history and physical examination.",
"<br><strong>Test:</strong> Tests for Legionella are negative. Culture of sputum, blood, or pleural fluid may grow other organisms that cause bacterial pneumonia.</p>",
"</dd>",
"<dt><a href='#Section1'>Hospital-acquired pneumonia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating features in history and physical examination.",
"<br><strong>Test:</strong> Tests for Legionella are negative. Other bacterial organisms may be cultured.</p>",
"</dd>",
"<dt><a href='#Section2'>Community-acquired pneumonia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating features in history and physical exam.",
"<br><strong>Test:</strong> Tests for Legionella are negative. Other bacterial organisms may be cultured.</p>",
"</dd>",
"<dt><a href='#Section3'>Influenza</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating features in history and physical examination.",
"<br><strong>Test:</strong> Tests for Legionella are negative. Viral serology or culture may be positive for influenza.</p>",
"</dd>",
"</dl>"].join("\n");