content=["<dl>",
"<dt><a href='#Section0'>Fracture</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Can be easily differentiated from grade 1 and 2 sprain and strain, but difficult to differentiate from grade 3 injuries.Usually needs additional tests to differentiate.",
"<br><strong>Test:</strong> Radiography in 2 planes usually can identify fracture and dislocations.</p>",
"</dd>",
"<dt><a href='#Section1'>Cartilage injury</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Difficult to differentiate clinically from joint sprain.",
"<br><strong>Test:</strong> MRI often required. Will show intact ligaments as well as the size and extent of the cartilage injury.</p>",
"</dd>",
"</dl>"].join("\n");