content=["<dl>",
"<dt><a href='#Section0'>Neoplasm (benign or malignant)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Features that may suggest neoplasm include unilateral symptoms, epistaxis/bleeding, crusting, cacosmia (perception of foul odour), periorbital oedema, displaced globe, double or reduced vision, ophthalmoplegia, severe frontal headaches, frontal swelling, signs of meningitis or focal neurology, and systemic symptoms such as weight loss.",
"<br><strong>Test:</strong> CT head defines extent and characteristics of the lesion(s). MRI can be performed in conjunction with CT for further evaluation.Biopsy confirms histology.</p>",
"</dd>",
"<dt><a href='#Section1'>Congenital lesions (e.g., encephalocele, concha bullosa)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating symptoms.",
"<br><strong>Test:</strong> CT and MRI head defines extent and characteristics of the lesion(s).</p>",
"</dd>",
"<dt><a href='#Section2'>Foreign body</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Usually sudden onset of unilateral symptoms. Epistaxis may feature.",
"<br><strong>Test:</strong> Nasendoscopy may allow identification and possible retrieval of foreign body.CT head may identify position, shape, and nature of foreign body.</p>",
"</dd>",
"</dl>"].join("\n");