content=["<dl>",
"<dt><a href='#Section0'>Benign stricture</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Usually associated with a long history of heartburn and slowly progressive dysphagia.",
"<br><strong>Test:</strong> Oesophagogastroduodenoscopy (OGD) shows stricture of benign aetiology.</p>",
"</dd>",
"<dt><a href='#Section1'>Achalasia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Long history of regurgitation with no history of heartburn. May be clinically indistinguishable from oesophageal cancer.",
"<br><strong>Test:</strong> Upper GI series shows a typical 'bird's beak' filling defect.OGD has low sensitivity for the diagnosis of achalasia, and is often reported to be normal in early achalasia.Oesophageal manometry shows incomplete relaxation of the lower oesophageal sphincter.</p>",
"</dd>",
"<dt><a href='#Section2'>Barrett's oesophagus</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Long-standing reflux. Dysphagia rare.",
"<br><strong>Test:</strong> OGD and biopsy will differentiate between benign intestinal metaplasia, dysplasia, and actual invasive cancer.</p>",
"</dd>",
"</dl>"].join("\n");