content=["<dl>",
"<dt><a href='#Section0'>Inborn errors of tetrahydrobiopterin (BH4) synthesis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Hyper-phenylalaninaemia can also result from rare defects in BH4. If untreated, these patients would develop mental retardation, movement disorders, seizures, and other neurological symptoms despite control of blood phenylalanine (phe) level. [9]  Much less common than PKU.",
"<br><strong>Test:</strong> Urine neopterin to biopterin ratio will be increased in defects of biopterin synthesis.Dihydropteridine reductase (DHPR) assay will be low in patients with DHPR deficiency.</p>",
"</dd>",
"<dt><a href='#Section1'>Hepatic dysfunction</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> May have hepatomegaly, jaundice.",
"<br><strong>Test:</strong> LFTs will be abnormal.Usually multiple elevations of plasma amino acids will be noted, not just phe.</p>",
"</dd>",
"<dt><a href='#Section2'>Extreme prematurity</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Baby will typically be in NICU. Small size and history of premature delivery.",
"<br><strong>Test:</strong> Usually multiple elevations of plasma amino acids will be noted, not just phe.</p>",
"</dd>",
"</dl>"].join("\n");