content=["<dl>",
"<dt><a href='#Section0'>Inflammatory bowel disease</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Typically, presents with prominent GI signs as well as evidence of systemic disease such as fever and weight loss.",
"<br><strong>Test:</strong> Colonoscopy/ileoscopy will show mucosal inflammation or ulceration. The biopsies will confirm inflammatory changes.</p>",
"</dd>",
"<dt><a href='#Section1'>Dermatitis, atopic</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> People with pinworm infection should not have evidence of inflammation or excoriation outside of the perineal area.",
"<br><strong>Test:</strong> Eosinophilia is uncommon in pinworm infection but may occur in eczema.</p>",
"</dd>",
"<dt><a href='#Section2'>Perirectal abscess</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Children with perirectal abscess are more likely to present with fever and pain. Abscess formation is extremely rare in pinworm infection.",
"<br><strong>Test:</strong> Acute-phase reactants are elevated in abscesses. Ultrasound/CT will confirm diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");