content=["<dl>",
"<dt><a href='#Section0'>Normal labour</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Bleeding is not usually severe and is darker.The fetus is not compromised.Labour progresses normally.",
"<br><strong>Test:</strong> The diagnosis is usually made clinically.Ultrasound will be normal.</p>",
"</dd>",
"<dt><a href='#Section1'>Placental abruption</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Usually painful.If the abruption is large, the uterus is rock-hard and the fetus will usually be compromised.Vaginal bleeding may range from absent to severe. Placental abruption may co-exist with placenta praevia. [46]  [47]",
"<br><strong>Test:</strong> Ultrasound may show abruption.</p>",
"</dd>",
"<dt><a href='#Section2'>Miscarriage</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> More common in early pregnancy (i.e., first and early second trimester).There is usually crampy abdominal pain as bleeding becomes heavier.Placental abruption may co-exist with miscarriage.",
"<br><strong>Test:</strong> The diagnosis is usually made clinically.Ultrasound may show products of conception.</p>",
"</dd>",
"</dl>"].join("\n");