content=["<dl>",
"<dt><a href='#Section0'>Myocardial infarction</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Presence of typical history of substernal chest pain with associated risk factors, signs, and symptoms.",
"<br><strong>Test:</strong> ECG may have ST segment changes that suggest infarction.Serum CK can be found as MM (muscle), MB (cardiac), and BB (brain) iso-enzymes.CK-MB greater than 5% of total CK levels suggests a cardiac source.</p>",
"</dd>",
"<dt><a href='#Section1'>Influenza</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Myalgia, accompanied by respiratory tract symptoms, fever, and headache.",
"<br><strong>Test:</strong> CK not elevated unless influenza viral myositis is present. This is very rare and is more likely in children.Culture, serology, or antigen detection immunoassays may be used, but are not sensitive or specific and need to be interpreted with the clinical findings.</p>",
"</dd>",
"<dt><a href='#Section2'>Fibromyalgia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Widespread body pain with areas of focal tenderness at designated points.Diagnosis made on clinical criteria.",
"<br><strong>Test:</strong> CK not elevated.</p>",
"</dd>",
"</dl>"].join("\n");