content=["<dl>",
"<dt><a href='#Section0'>Maturity onset diabetes of the young (MODY)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Strong family history.Slow onset.Absence of ketoacidosis.Response to sulphonylurea drugs.",
"<br><strong>Test:</strong> C-peptide present.Anti-glutamic acid decarboxylase (GAD) antibodies absent.</p>",
"</dd>",
"<dt><a href='#Section1'>Type 2 diabetes</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Typically, signs of insulin resistance (such as acanthosis nigricans) should be sought and in their absence clinical suspicion of type 1 diabetes is greater.Signs of more marked insulin deficiency (for example, glycaemic lability as well as susceptibility to ketosis) raise suspicion of type 1 diabetes.Older age and slow onset, obesity, a strong family history, absence of ketoacidosis, and initial response to oral anti-hyperglycaemic drugs are typical of type 2 diabetes.",
"<br><strong>Test:</strong> C-peptide present.Anti-glutamic acid decarboxylase (GAD) antibodies absent.Testing for C-peptide and GAD usually not required.</p>",
"</dd>",
"</dl>"].join("\n");