content=["<dl>",
"<dt><a href='#Section0'>Mild haemophilia A</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Bleeding symptoms may be similar, although patients with VWD tend to have more mucosal bleeding symptoms.By family history, VWD is inherited in an autosomal pattern and haemophilia in an X-linked pattern.However, because of the high mutation rate in haemophilia A and because of variable expressivity in VWD, a positive family history may be absent in both.",
"<br><strong>Test:</strong> Patients with haemophilia A have decreased factor VIII, but normal VWF antigen and activity. For VWD all 3 are decreased. Special binding studies or DNA analysis is required to distinguish type 2N VWD from hemophilia A.</p>",
"</dd>",
"<dt><a href='#Section1'>Inherited platelet function disorder</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Both platelet function disorders and VWD have predominant mucosal bleeding symptoms.Rare severe platelet function disorders such as Glanzmann's thrombasthenia and Bernard-Soulier syndrome are autosomal recessive in inheritance, but most disorders are autosomal dominant.",
"<br><strong>Test:</strong> Platelet aggregometry is abnormal in inherited platelet disorders and normal in VWD.In non-type 2B VWD there may be decreased sensitivity to ristocetin induced platelet agglutination, but this is less sensitive for the diagnosis of VWD than the ristocetin cofactor assay.</p>",
"</dd>",
"</dl>"].join("\n");