interactions["aminocaproic-acid"]=["aminocaproic-acid", {"a": {"abbokinase open-cath": "2",
 "anistreplase": "2",
 "autoplex t": "3",
 "anti-inhibitor coagulant complex": "3",
 "activase": "2",
 "abbokinase": "2",
 "alteplase": "2"}, "c": {"cathflo activase": "2"}, "b": {"bebulin vh": "3",
 "brilinta": "1"}, "e": {"eminase": "2"}, "f": {"feiba vh": "3",
 "factor ix complex": "3",
 "febia nf": "3"}, "k": {"kinlytic": "2",
 "kabikinase": "2",
 "konyne 80": "3"}, "p": {"proplex t": "3",
 "profilnine sd": "3"}, "s": {"streptase": "2",
 "streptokinase": "2"}, "r": {"retavase": "2",
 "retavase half-kit": "2",
 "reteplase": "2"}, "u": {"urokinase": "2"}, "t": {"ticagrelor": "1",
 "tenecteplase": "2",
 "tretinoin": "3",
 "tnkase": "2"}, "v": {"vesanoid": "3"}}];