interactions["antipyrine-benzocaine-phenylephrine-otic,otogesic"]=["antipyrine-benzocaine-phenylephrine-otic,otogesic", {"c": {"cafatine": "2",
 "cafatine pb": "2",
 "caffeine/ergotamine": "2",
 "cafetrate": "2",
 "cafergot": "2"}, "b": {"belcomp-pb": "2",
 "bellaphen-s": "2",
 "bellergal-s": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "bellamine": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "bellamor": "2",
 "bellaspas": "2",
 "bel-tabs": "2",
 "bellamine s": "2",
 "bel-phen-ergot": "2"}, "e": {"ergotrate": "2",
 "ergocaffpb": "2",
 "ergotamine": "2",
 "ergomar": "2",
 "e-caff p-b": "2",
 "ergocomp-pb": "2",
 "ergocaf-pb": "2",
 "ercaf": "2",
 "ergotrate maleate": "2",
 "eperbel-s": "2",
 "ergonovine": "2"}, "d": {"dihydroergotamine": "2",
 "duragal-s": "2",
 "d.h.e. 45": "2"}, "m": {"midodrine": "2",
 "migergot": "2",
 "methergine": "2",
 "migranal": "2",
 "migracet-pb": "2",
 "methylergonovine": "2",
 "micomp-pb": "2"}, "o": {"oxytocin": "2",
 "orvaten": "2"}, "p": {"pitocin": "2",
 "proamatine": "2"}, "s": {"syntocinon": "2",
 "spastrin": "2"}, "w": {"wigraine": "2"}}];