interactions["aprotinin,trasylol"]=["aprotinin,trasylol", {"a": {"activase": "2",
 "abbokinase open-cath": "2",
 "abbokinase": "2",
 "alteplase": "2",
 "anistreplase": "2"}, "c": {"cathflo activase": "2"}, "e": {"eminase": "2"}, "k": {"kinlytic": "2",
 "kabikinase": "2"}, "s": {"streptase": "2",
 "streptokinase": "2"}, "r": {"retavase": "2",
 "retavase half-kit": "2",
 "reteplase": "2"}, "u": {"urokinase": "2"}, "t": {"tnkase": "2",
 "tenecteplase": "2",
 "tretinoin": "3"}, "v": {"vesanoid": "3"}}];