interactions["bacitracin-neomycin-polymyxin-b-topical,neosporin"]=["bacitracin-neomycin-polymyxin-b-topical,neosporin", {"a": {"amikin": "2",
 "amikacin": "2",
 "atracurium": "2",
 "amikin pediatric": "2",
 "arduan": "2",
 "anectine flo-pack": "2",
 "anectine": "2"}, "c": {"cidomycin": "2",
 "cisatracurium": "2"}, "d": {"doxacurium": "2"}, "g": {"garamycin": "2",
 "gentamicin": "2"}, "k": {"kanamycin": "2",
 "kantrex": "2"}, "m": {"mivacron": "2",
 "mycifradin": "2",
 "metocurine": "2",
 "mivacurium": "2",
 "metubine iodide": "2"}, "n": {"nebcin": "2",
 "neo-fradin": "2",
 "netromycin": "2",
 "nimbex": "2",
 "netilmicin": "2",
 "nebcin pediatric": "2",
 "norcuron": "2",
 "nuromax": "2",
 "neomycin": "2",
 "neo-tab": "2"}, "q": {"quelicin chloride": "2",
 "quelicin": "2"}, "p": {"pavulon": "2",
 "pipecuronium": "2",
 "pancuronium": "2"}, "s": {"streptomycin": "2",
 "succinylcholine": "2",
 "septopal": "2"}, "r": {"raplon": "2",
 "rocuronium": "2",
 "rapacuronium": "2"}, "t": {"tobramycin": "2",
 "tracrium": "2",
 "tobi": "2",
 "tubocurarine": "2"}, "v": {"vecuronium": "2"}, "z": {"zemuron": "2"}}];