interactions["benzoyl-peroxide-topical,brevoxyl"]=["benzoyl-peroxide-topical,brevoxyl", {"a": {"aczone": "1",
 "avita": "2",
 "accutane": "2",
 "altinac": "2",
 "atralin": "2",
 "amnesteem": "2"}, "c": {"claravis": "2",
 "clindamycin/tretinoin topical": "2"}, "d": {"dapsone topical": "1"}, "f": {"fluocinolone/hydroquinone/tretinoin topical": "2"}, "i": {"isotretinoin": "2"}, "m": {"myorisan": "2",
 "mequinol/tretinoin topical": "2"}, "s": {"solage": "2",
 "sotret": "2",
 "stievaa": "2",
 "stie vaa forte": "2"}, "r": {"retin-a and renova": "2",
 "retin-a": "2",
 "retin a micro": "2",
 "retisol-a": "2",
 "refissa": "2",
 "renova": "2"}, "t": {"tretinoin topical": "2",
 "tri-luma": "2",
 "tretin-x": "2"}, "v": {"veltin": "2",
 "vitinoin": "2"}, "z": {"ziana": "2"}}];