interactions["bicalutamide"]=["bicalutamide", {"a": {"arava": "3",
 "avonex": "2",
 "anisindione": "1",
 "avonex prefilled syringe": "2",
 "atripla": "2"}, "c": {"clolar": "2",
 "clofarabine": "2",
 "coumadin": "1",
 "cisapride": "2"}, "b": {"betaseron": "2",
 "black cohosh": "2"}, "e": {"embeda": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "extavia": "2",
 "efavirenz": "2"}, "d": {"dicumarol": "1",
 "depade": "2"}, "f": {"folex pfs": "2"}, "i": {"interferon beta-1a": "2",
 "interferon beta-1b": "2"}, "j": {"jantoven": "1"}, "m": {"methotrexate": "2",
 "morphine/naltrexone": "2",
 "miradon": "1",
 "methotrexate lpf sodium": "2",
 "menopause support": "2"}, "l": {"leflunomide": "3"}, "n": {"naltrexone": "2"}, "p": {"pseudoephedrine/terfenadine": "2",
 "propulsid": "2"}, "s": {"seldane-d": "2",
 "seldane": "2",
 "sustiva": "2"}, "r": {"revia": "2",
 "rheumatrex dose pack": "2",
 "rebif": "2"}, "t": {"terfenadine": "2",
 "trexall": "2",
 "tabloid": "2",
 "thioguanine": "2"}, "w": {"warfarin": "1"}, "v": {"vivitrol": "2"}}];