interactions["capsaicin-topical,capsin"]=["capsaicin-topical,capsin", {"a": {"accuretic": "1",
 "aceon": "1",
 "amlobenz": "1",
 "altace": "1",
 "amlodipine/benazepril": "1",
 "accupril": "1"}, "c": {"captopril/hydrochlorothiazide": "1",
 "capozide": "1",
 "capozide 25/25": "1",
 "capoten": "1",
 "capozide 25/15": "1",
 "capozide 50/25": "1",
 "captopril": "1",
 "capozide 50/15": "1"}, "b": {"benazepril/hydrochlorothiazide": "1",
 "benazepril": "1"}, "e": {"enalapril/hydrochlorothiazide": "1",
 "enalapril/felodipine": "1",
 "enalapril": "1"}, "d": {"diltiazem/enalapril": "1"}, "f": {"fosinopril/hydrochlorothiazide": "1",
 "fosinopril": "1"}, "h": {"hydrochlorothiazide/moexipril": "1",
 "hydrochlorothiazide/quinapril": "1",
 "hydrochlorothiazide/lisinopril": "1"}, "m": {"monopril": "1",
 "mavik": "1",
 "moexipril": "1",
 "monopril hct": "1"}, "l": {"lexxel": "1",
 "lotensin hct": "1",
 "lotrel": "1",
 "lotensin": "1",
 "lisinopril": "1"}, "q": {"quinapril": "1",
 "quinaretic": "1"}, "p": {"prinzide": "1",
 "perindopril": "1",
 "prinivil": "1"}, "r": {"ramipril": "1"}, "u": {"univasc": "1",
 "uniretic": "1"}, "t": {"tarka": "1",
 "trandolapril": "1",
 "teczem": "1",
 "trandolapril/verapamil": "1"}, "v": {"vaseretic 10-25": "1",
 "vaseretic": "1",
 "vasotec": "1",
 "vaseretic 5-12.5": "1"}, "z": {"zestoretic": "1",
 "zestril": "1"}}];