interactions["cetuximab"]=["cetuximab", {"a": {"amoxicillin/clarithromycin/lansoprazole": "2",
 "adrucil": "2",
 "aciphex": "2"}, "c": {"capecitabine": "2",
 "cisplatin": "2",
 "carboplatin novaplus": "2",
 "carboplatin": "2"}, "e": {"eloxatin": "2",
 "esomeprazole": "2",
 "esomeprazole/naproxen": "2"}, "d": {"dexlansoprazole": "2",
 "dexilant": "2"}, "f": {"fluorouracil": "2"}, "k": {"kapidex": "2"}, "l": {"lansoprazole": "2",
 "lansoprazole/naproxen": "2"}, "o": {"oxaliplatin": "2",
 "omesec": "2",
 "omeprazole": "2",
 "omeprazole/sodium bicarbonate": "2"}, "n": {"nexium iv": "2",
 "nexium": "2"}, "p": {"protonix iv": "2",
 "platinol": "2",
 "prevacid naprapac 375": "2",
 "prevacid iv": "2",
 "paraplatin": "2",
 "prevacid": "2",
 "prilosec": "2",
 "platinol-aq": "2",
 "prevacid naprapac 500": "2",
 "protonix": "2",
 "prevacid 24hr": "2",
 "prevpac": "2",
 "prilosec otc": "2",
 "prevacid otc": "2",
 "prevacid naprapac": "2",
 "prevacid solutab": "2",
 "pantoprazole": "2"}, "r": {"rabeprazole": "2"}, "t": {"thalomid": "3",
 "thalidomide": "3"}, "v": {"vimovo": "2"}, "x": {"xeloda": "2"}, "z": {"zegerid otc": "2",
 "zegerid": "2"}}];  