interactions["chaparral"]=["chaparral", {"a": {"avonex": "2",
 "arava": "3",
 "avonex prefilled syringe": "2",
 "atripla": "2"}, "c": {"clolar": "2",
 "clofarabine": "2"}, "b": {"betaseron": "2",
 "black cohosh": "2"}, "e": {"embeda": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "extavia": "2",
 "efavirenz": "2"}, "d": {"depade": "2"}, "f": {"folex pfs": "2"}, "i": {"interferon beta-1a": "2",
 "interferon beta-1b": "2"}, "m": {"methotrexate": "2",
 "morphine/naltrexone": "2",
 "methotrexate lpf sodium": "2",
 "menopause support": "2"}, "l": {"leflunomide": "3"}, "n": {"naltrexone": "2"}, "s": {"sustiva": "2"}, "r": {"revia": "2",
 "rheumatrex dose pack": "2",
 "rebif": "2"}, "t": {"trexall": "2",
 "tabloid": "2",
 "thioguanine": "2"}, "v": {"vivitrol": "2"}}];