interactions["chloroprocaine,nesacaine"]=["chloroprocaine,nesacaine", {"a": {"azulfidine en-tabs": "2",
 "azulfidine": "2",
 "amphadase": "1"}, "c": {"cotrim": "2",
 "cotrim ds": "2",
 "co-trimoxazole": "2",
 "cotrim pediatric": "2"}, "b": {"bactrim iv": "2",
 "bactrim pediatric": "2",
 "bactrim": "2",
 "bactrim ds": "2",
 "bupivacaine liposome": "2",
 "bethaprim pediatric": "2",
 "bethaprim": "2"}, "e": {"exparel": "2"}, "g": {"gantanol": "2"}, "f": {"fansidar": "2"}, "h": {"hyaluronidase": "1",
 "hylenex": "1",
 "hydase": "1"}, "p": {"pyrimethamine/sulfadoxine": "2",
 "phenazopyridine/sulfamethoxazole": "2"}, "s": {"sulfasalazine": "2",
 "sulfamethoxazole": "2",
 "septra": "2",
 "smz-tmp ds": "2",
 "sulfamethoxazole/trimethoprim": "2",
 "sulfazine": "2",
 "sulfatrim pediatric": "2",
 "sulfadiazine": "2",
 "septra iv": "2",
 "septra ds": "2",
 "sulfadoxine": "2",
 "sulfatrim": "2"}, "u": {"uroplus ds": "2",
 "uroplus": "2"}, "w": {"wydase": "1"}, "v": {"vitrase": "1"}}];