interactions["ciclesonide-nasal,omnaris"]=["ciclesonide-nasal,omnaris", {"a": {"amprenavir": "2",
 "agenerase": "2",
 "accesspak for hiv pep expanded with viracept": "2",
 "amoxicillin/clarithromycin/lansoprazole": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "atazanavir": "2"}, "c": {"crixivan": "2",
 "conivaptan": "2",
 "clarithromycin": "2"}, "b": {"boceprevir": "2",
 "biaxin xl": "2",
 "biaxin": "2"}, "e": {"emtricitabine/nelfinavir/tenofovir": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2"}, "d": {"darunavir": "2",
 "delavirdine": "2"}, "f": {"fosamprenavir": "2"}, "i": {"itraconazole": "2",
 "incivek": "2",
 "indinavir": "2"}, "k": {"ketek": "2",
 "kaletra": "2",
 "ketek pak": "2",
 "ketoconazole": "2"}, "m": {"miconazole": "2"}, "l": {"lopinavir/ritonavir": "2",
 "lexiva": "2"}, "o": {"oravig": "2"}, "n": {"norvir soft gelatin": "2",
 "norvir": "2",
 "noxafil": "2",
 "nefazodone": "2",
 "nelfinavir": "2",
 "nizoral": "2"}, "p": {"posaconazole": "2",
 "prezista": "2",
 "prevpac": "2"}, "s": {"serzone": "2",
 "sporanox pulsepak": "2",
 "sporanox": "2"}, "r": {"reyataz": "2",
 "ritonavir": "2",
 "rescriptor": "2"}, "t": {"telaprevir": "2",
 "telzir": "2",
 "tao": "2",
 "telithromycin": "2",
 "troleandomycin": "2"}, "v": {"viracept": "2",
 "vaprisol": "2",
 "victrelis": "2",
 "vfend": "2",
 "voriconazole": "2"}}];