interactions["clindamycin-topical,clindets"]=["clindamycin-topical,clindets", {"a": {"atracurium": "2",
 "arduan": "2",
 "anectine flo-pack": "2",
 "anectine": "2"}, "c": {"cisatracurium": "2"}, "d": {"doxacurium": "2"}, "m": {"mivacron": "2",
 "metocurine": "2",
 "mivacurium": "2",
 "metubine iodide": "2"}, "n": {"norcuron": "2",
 "nimbex": "2",
 "nuromax": "2"}, "q": {"quelicin chloride": "2",
 "quelicin": "2"}, "p": {"pavulon": "2",
 "pipecuronium": "2",
 "pancuronium": "2"}, "s": {"succinylcholine": "2"}, "r": {"raplon": "2",
 "rocuronium": "2",
 "rapacuronium": "2"}, "t": {"tracrium": "2",
 "tubocurarine": "2"}, "v": {"vecuronium": "2"}, "z": {"zemuron": "2"}}];