interactions["collagenase-topical,santyl"]=["collagenase-topical,santyl", {"s": {"silvadene cream 1%": "2",
 "silvasorb": "2",
 "silver sulfadiazine topical": "2",
 "silvadene": "2",
 "silver topical": "2",
 "silver/zinc oxide topical": "2",
 "ssd af": "2",
 "silver nitrate topical": "2",
 "ssd": "2"}, "m": {"mersol": "2"}, "t": {"thermazene": "2",
 "thimerosal topical": "2"}}];