interactions["dextrothyroxine-sodium,choloxin"]=["dextrothyroxine-sodium,choloxin", {"a": {"aventyl hydrochloride": "1",
 "amoxapine": "1",
 "amitriptyline/chlordiazepoxide": "1",
 "anafranil": "1",
 "asendin": "1",
 "amitriptyline/perphenazine": "1",
 "amitriptyline": "1",
 "adapin": "1",
 "anisindione": "2"}, "c": {"clomipramine": "1",
 "coumadin": "2"}, "e": {"etrafon forte": "1",
 "elavil": "1",
 "endep": "1",
 "etrafon": "1"}, "d": {"duo-vil": "1",
 "desipramine": "1",
 "doxepin": "1",
 "dicumarol": "2"}, "i": {"imipramine": "1"}, "j": {"jantoven": "2"}, "m": {"miradon": "2"}, "l": {"limbitrol ds": "1",
 "limbitrol": "1"}, "n": {"norpramin": "1",
 "nortriptyline": "1"}, "p": {"pamelor": "1",
 "protriptyline": "1"}, "s": {"sinequan": "1",
 "sirolimus": "2",
 "surmontil": "1",
 "silenor": "1"}, "r": {"rapamune": "2"}, "t": {"tofranil": "1",
 "triavil": "1",
 "torisel": "2",
 "trimipramine": "1",
 "tofranil-pm": "1",
 "temsirolimus": "2"}, "w": {"warfarin": "2"}, "v": {"vivactil": "1",
 "vanatrip": "1"}}];