interactions["docusate,dionex"]=["docusate,dionex", {"a": {"alpha keri": "2",
 "alphabath": "2",
 "aluminum hydroxide/mineral oil": "2"}, "c": {"chocolaxed": "2",
 "caroid laxative": "2",
 "cascara sagrada/phenolphthalein": "2"}, "e": {"espotabs": "2",
 "ex-lax extra gentle": "2"}, "d": {"docusate/phenolphthalein": "2",
 "docucal-p": "2",
 "doxidan softgel laxative plus stool softener": "2",
 "dialose plus": "2"}, "f": {"fletchers child laxative cherry": "2",
 "femilax": "2",
 "fleet mineral oil enema": "2",
 "feminine lax": "2",
 "femintrol": "2"}, "h": {"haley's m-o": "2"}, "k": {"kondremul plain": "2",
 "kondremul": "2",
 "kondremul with phenolphtalein": "2"}, "m": {"milkinol": "2",
 "modane plus": "2",
 "mineral oil/phenolphthalein": "2",
 "magnesium hydroxide/mineral oil": "2",
 "medilax": "2",
 "mineral oil": "2",
 "muri-lube": "2"}, "l": {"liqui doss": "2",
 "lanolin/mineral oil topical": "2"}, "n": {"nephrox": "2"}, "p": {"phillips' haleys m-o": "2",
 "phenolax": "2",
 "prulet": "2",
 "phillips gel": "2",
 "phenolphthalein": "2"}, "u": {"unilax": "2"}, "t": {"thera derm": "2"}}];