interactions["emtricitabine,emtriva"]=["emtricitabine,emtriva", {"a": {"avonex": "2",
 "arava": "3",
 "avonex prefilled syringe": "2",
 "atripla": "2"}, "c": {"copegus": "2",
 "clolar": "2",
 "clofarabine": "2"}, "b": {"betaseron": "2",
 "baraclude": "2",
 "black cohosh": "2"}, "e": {"efavirenz": "2",
 "eribulin": "1",
 "entecavir": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "embeda": "2",
 "extavia": "2"}, "d": {"depade": "2"}, "f": {"folex pfs": "2"}, "i": {"interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "interferon alfa-2b/ribavirin": "2"}, "h": {"halaven": "1"}, "m": {"methotrexate": "2",
 "morphine/naltrexone": "2",
 "methotrexate lpf sodium": "2",
 "menopause support": "2"}, "l": {"leflunomide": "3"}, "n": {"naltrexone": "2"}, "s": {"sustiva": "2"}, "r": {"rheumatrex dose pack": "2",
 "rebif": "2",
 "ribatab": "2",
 "revia": "2",
 "ribasphere": "2",
 "ribapak": "2",
 "rebetol": "2",
 "rebetron": "2",
 "ribavirin": "2"}, "t": {"trexall": "2",
 "tabloid": "2",
 "thioguanine": "2"}, "v": {"virazole": "2",
 "vivitrol": "2"}}];