interactions["finasteride,proscar"]=["finasteride,proscar", {"a": {"accesspak for hiv pep expanded with viracept": "2"}, "c": {"cardizem monovial": "2",
 "cartia xt": "2",
 "cardizem sr": "2",
 "cardizem cd": "2",
 "cardizem la": "2",
 "cardizem": "2"}, "e": {"emtricitabine/nelfinavir/tenofovir": "2"}, "d": {"diltiazem/enalapril": "2",
 "dilacor xr": "2",
 "diltiazem hydrochloride cd": "2",
 "diltiazem hydrochloride sr": "2",
 "diflucan": "2",
 "diltiazem": "2",
 "diltzac": "2",
 "dilt-xr": "2",
 "diltiazem hydrochloride xt": "2",
 "diltia xt": "2",
 "diltiazem hydrochloride xr": "2"}, "f": {"fortovase": "2",
 "fluconazole": "2",
 "fluvoxamine": "2"}, "i": {"invirase": "2",
 "itraconazole": "2"}, "h": {"hytrin": "1"}, "m": {"matzim la": "2"}, "l": {"luvox cr": "2",
 "luvox": "2"}, "n": {"noxafil": "2",
 "nelfinavir": "2",
 "nefazodone": "2"}, "p": {"prograf": "2",
 "posaconazole": "2"}, "s": {"sirolimus": "2",
 "sporanox pulsepak": "2",
 "serzone": "2",
 "saquinavir": "2",
 "sporanox": "2"}, "r": {"rapamune": "2"}, "t": {"tiazac": "2",
 "teczem": "2",
 "terazosin": "1",
 "taztia xt": "2",
 "tacrolimus": "2"}, "v": {"viracept": "2",
 "vfend": "2",
 "voriconazole": "2"}}];