interactions["ganirelix"]=["ganirelix", {"a": {"apl (chorionic gonadotropin (hcg))": "2"}, "c": {"chorex (chorionic gonadotropin (hcg))": "2",
 "choron-10 (chorionic gonadotropin (hcg))": "2",
 "chorigon (chorionic gonadotropin (hcg))": "2",
 "chorionic gonadotropin (chorionic gonadotropin (hcg))": "2",
 "chorionic gonadotropin": "2"}, "b": {"bravelle": "2"}, "g": {"gonal-f pen": "2",
 "gonal-f": "2",
 "gonic (chorionic gonadotropin (hcg))": "2",
 "gonal-f rff": "2",
 "gonal-f rff pen": "2",
 "gonadorelin": "2"}, "f": {"follistim aq": "2",
 "follistim": "2",
 "follistim aq cartridge": "2",
 "follistim/antagon": "2",
 "follicle stimulating hormone/ganirelix": "2",
 "factrel": "2",
 "fertinex": "2",
 "follicle stimulating hormone": "2"}, "h": {"hcg (chorionic gonadotropin (hcg))": "2",
 "humegon": "2"}, "m": {"menopur": "2",
 "metrodin": "2",
 "menotropins": "2"}, "l": {"lutrepulse": "2"}, "o": {"ovidrel (chorionic gonadotropin (hcg))": "2"}, "n": {"novarel (chorionic gonadotropin (hcg))": "2"}, "p": {"profasi (chorionic gonadotropin (hcg))": "2",
 "pregnyl (chorionic gonadotropin (hcg))": "2",
 "pergonal": "2",
 "profasi hp (chorionic gonadotropin (hcg))": "2",
 "puregon": "2"}, "r": {"repronex": "2"}, "u": {"urofollitropin": "2"}, "t": {"trelstar depot": "2",
 "triptorelin": "2",
 "trelstar": "2",
 "trelstar la": "2"}}];