interactions["mebendazole,vermox"]=["mebendazole,vermox", {"a": {"ari sodium iodide (i123) 100-750 mbq": "2",
 "ari sodium iodide (i123) 1-12 mbq": "2"}, "c": {"cerebyx": "1",
 "carbatrol": "1",
 "cimetidine": "1",
 "carbamazepine": "1"}, "b": {"bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2"}, "e": {"equetro": "1",
 "equaline acid reducer": "1",
 "ethotoin": "1",
 "epitol": "1"}, "d": {"dilantin": "1"}, "f": {"flagyl 375": "2",
 "flagyl er": "2",
 "flagyl": "2",
 "flagyl iv": "2",
 "fosphenytoin": "1"}, "i": {"iodotope": "2"}, "h": {"helidac": "2"}, "m": {"mesantoin": "1",
 "metro": "2",
 "metro iv": "2",
 "mephenytoin": "1",
 "metryl": "2",
 "metronidazole": "2"}, "p": {"phenytoin": "1",
 "pylera": "2",
 "peganone": "1",
 "phenytek": "1",
 "protostat": "2",
 "phenytoin sodium, prompt": "1"}, "s": {"sodium iodide-i-131": "2",
 "sodium iodide i-123": "2"}, "t": {"tegretol": "1",
 "tegretol xr": "1",
 "tagamet hb": "1",
 "tagamet": "1"}}];