interactions["niclosamide"]=["niclosamide", {"a": {"ari sodium iodide (i123) 100-750 mbq": "2",
 "azilect": "2",
 "anagrelide": "2",
 "alosetron": "2",
 "agrylin": "2",
 "ari sodium iodide (i123) 1-12 mbq": "2"}, "c": {"chirocaine": "2",
 "cymbalta": "2"}, "b": {"bendamustine": "2"}, "d": {"duloxetine": "2"}, "i": {"iodotope": "2"}, "l": {"levobupivacaine": "2",
 "lotronex": "2"}, "s": {"sodium iodide-i-131": "2",
 "sodium iodide i-123": "2"}, "r": {"repreve": "2",
 "requip starter kit": "2",
 "requip xl": "2",
 "ramelteon": "2",
 "ropinirole": "2",
 "rasagiline": "2",
 "requip": "2",
 "requip starter pack": "2",
 "requip follow on pack": "2",
 "rozerem": "2"}, "t": {"treanda": "2",
 "tizanidine": "3"}, "z": {"zanaflex": "3"}}];