interactions["panitumumab,vectibix"]=["panitumumab,vectibix", {"a": {"arsenic trioxide": "3",
 "amoxicillin/clarithromycin/lansoprazole": "2",
 "amiodarone": "3",
 "aciphex": "2",
 "avastin": "3"}, "c": {"cordarone iv": "3",
 "cordarone": "3",
 "camptosar": "3"}, "b": {"bevacizumab": "3"}, "e": {"esomeprazole": "2",
 "esomeprazole/naproxen": "2"}, "d": {"droperidol": "3",
 "dexlansoprazole": "2",
 "dronedarone": "3",
 "disopyramide": "2",
 "dofetilide": "3",
 "droperidol/fentanyl": "3",
 "dexilant": "2"}, "g": {"geodon": "3"}, "i": {"innovar": "3",
 "inapsine": "3",
 "irinotecan": "3"}, "k": {"kapidex": "2"}, "m": {"multaq": "3"}, "l": {"lansoprazole": "2",
 "lansoprazole/naproxen": "2",
 "levomethadyl acetate": "3"}, "o": {"orap": "3",
 "orlaam": "3",
 "omesec": "2",
 "omeprazole": "2",
 "omeprazole/sodium bicarbonate": "2"}, "n": {"norpace cr": "2",
 "norpace": "2",
 "nexium iv": "2",
 "nexium": "2",
 "nexterone": "3"}, "p": {"protonix": "2",
 "prevacid naprapac 375": "2",
 "prevacid iv": "2",
 "pimozide": "3",
 "prevacid": "2",
 "prilosec": "2",
 "pacerone": "3",
 "prevacid naprapac 500": "2",
 "protonix iv": "2",
 "prevacid 24hr": "2",
 "prevpac": "2",
 "prilosec otc": "2",
 "prevacid otc": "2",
 "prevacid naprapac": "2",
 "prevacid solutab": "2",
 "pantoprazole": "2"}, "r": {"rabeprazole": "2"}, "t": {"tikosyn": "3",
 "trisenox": "3"}, "v": {"vimovo": "2"}, "z": {"ziprasidone": "3",
 "zegerid otc": "2",
 "zegerid": "2"}}];