interactions["papain-urea-topical,gladase"]=["papain-urea-topical,gladase", {"h": {"hydrogen peroxide topical": "2"}, "m": {"mersol": "2"}, "o": {"orajel antiseptic mouth sore rinse": "2"}, "p": {"peroxyl": "2",
 "perimax perio rinse": "2",
 "proxacol": "2"}, "s": {"silvadene cream 1%": "2",
 "silvasorb": "2",
 "silver sulfadiazine topical": "2",
 "silvadene": "2",
 "silver topical": "2",
 "silver/zinc oxide topical": "2",
 "ssd af": "2",
 "silver nitrate topical": "2",
 "ssd": "2"}, "t": {"thermazene": "2",
 "thimerosal topical": "2"}}];