interactions["phytonadione,mephyton"]=["phytonadione,mephyton", {"a": {"alphabath": "1",
 "anisindione": "2",
 "alpha keri": "1",
 "alli": "1",
 "aluminum hydroxide/mineral oil": "1"}, "c": {"cholestyramine": "2",
 "coumadin": "2",
 "colesevelam": "2",
 "cholestyramine light": "2"}, "d": {"dicumarol": "2"}, "f": {"fleet mineral oil enema": "1"}, "h": {"haley's m-o": "1"}, "k": {"kondremul plain": "1",
 "kondremul": "1",
 "kondremul with phenolphtalein": "1"}, "j": {"jantoven": "2"}, "m": {"milkinol": "1",
 "muri-lube": "1",
 "mineral oil/phenolphthalein": "1",
 "magnesium hydroxide/mineral oil": "1",
 "mineral oil": "1",
 "miradon": "2"}, "l": {"locholest": "2",
 "liqui doss": "1",
 "locholest light": "2",
 "lanolin/mineral oil topical": "1"}, "o": {"orlistat": "1"}, "n": {"nephrox": "1"}, "q": {"questran light": "2",
 "questran": "2"}, "p": {"phillips' haleys m-o": "1",
 "prevalite": "2"}, "t": {"thera derm": "1"}, "w": {"welchol": "2",
 "warfarin": "2"}, "x": {"xenical": "1"}}];