interactions["porfimer,photofrin"]=["porfimer,photofrin", {"a": {"aminolevulinic acid topical": "2",
 "aquavite-e": "2",
 "aqua gem-e": "2",
 "amino-opti-e": "2",
 "aquasol e": "2",
 "aqua-e": "2",
 "alpha e": "2"}, "c": {"centrum singles-vitamin e": "2"}, "e": {"e-gems": "2",
 "e-400 clear": "2",
 "e-600": "2",
 "e pherol": "2"}, "m": {"metvixia": "2",
 "methyl aminolevulinate topical": "2",
 "methoxsalen": "2"}, "l": {"levulan kerastick": "2"}, "o": {"oxsoralen-ultra": "2"}, "n": {"nutr-e-sol": "2"}, "u": {"uvadex": "2"}, "t": {"thalomid": "3",
 "thalidomide": "3"}, "v": {"visudyne": "2",
 "vitamin e": "2",
 "vita-plus e natural": "2",
 "verteporfin": "2"}, "8": {"8-mop": "2"}}];