interactions["potassium-aminobenzoate,potaba"]=["potassium-aminobenzoate,potaba", {"a": {"azo-truxazole": "3",
 "azulfidine": "3",
 "azulfidine en-tabs": "3"}, "c": {"cotrim": "3",
 "cotrim ds": "3",
 "co-trimoxazole": "3",
 "cotrim pediatric": "3"}, "b": {"bactrim iv": "3",
 "bactrim pediatric": "3",
 "bactrim": "3",
 "bactrim ds": "3",
 "bethaprim pediatric": "3",
 "bethaprim": "3"}, "e": {"eplerenone": "3",
 "e s p": "3",
 "erythromycin/sulfisoxazole": "3",
 "eryzole": "3"}, "g": {"gantrisin": "3",
 "gantrisin pediatric": "3",
 "gantanol": "3"}, "f": {"fansidar": "3"}, "i": {"inspra": "3"}, "o": {"oxytetracycline/phenazopyridine/sulfamethizole": "3"}, "p": {"phenazopyridine/sulfisoxazole": "3",
 "pyrimethamine/sulfadoxine": "3",
 "phenazopyridine/sulfamethoxazole": "3",
 "pediazole": "3"}, "s": {"sulfasalazine": "3",
 "sulfamethoxazole": "3",
 "sulfimycin": "3",
 "sulfamethizole": "3",
 "septra": "3",
 "smz-tmp ds": "3",
 "sulfamethoxazole/trimethoprim": "3",
 "sulfazine": "3",
 "sulfatrim pediatric": "3",
 "sulfadiazine": "3",
 "septra iv": "3",
 "septra ds": "3",
 "sulfadoxine": "3",
 "sulfatrim": "3",
 "sulfisoxazole": "3"}, "u": {"uroplus ds": "3",
 "urobiotic-250": "3",
 "uroplus": "3"}, "t": {"thiosulfil forte": "3",
 "tija": "3",
 "truxazole": "3"}}];