interactions["prilocaine"]=["prilocaine", {"a": {"amiodarone": "2",
 "amphadase": "1"}, "c": {"cordarone iv": "2",
 "corvert": "2",
 "cordarone": "2"}, "b": {"bretylol": "2",
 "betapace af": "2",
 "bretylium": "2",
 "betapace": "2"}, "d": {"depodur": "2",
 "dofetilide": "2"}, "i": {"ibutilide": "2"}, "h": {"hyaluronidase": "1",
 "hylenex": "1",
 "hydase": "1"}, "m": {"morphine liposomal": "2"}, "n": {"nexterone": "2"}, "p": {"pacerone": "2"}, "s": {"sotalol": "2",
 "sorine": "2",
 "sotalol hydrochloride af": "2"}, "t": {"tikosyn": "2"}, "w": {"wydase": "1"}, "v": {"vitrase": "1"}}];