interactions["pyrazinamide"]=["pyrazinamide", {"a": {"aloprim": "1",
 "avonex": "2",
 "arava": "3",
 "allopurinol": "1",
 "amersham indium (111in) oxine": "2",
 "atripla": "2",
 "avonex prefilled syringe": "2"}, "c": {"clolar": "2",
 "cyclosporine": "2",
 "clofarabine": "2"}, "b": {"betaseron": "2",
 "bcg": "3",
 "black cohosh": "2"}, "e": {"embeda": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "extavia": "2",
 "efavirenz": "2"}, "d": {"depade": "2"}, "g": {"gengraf": "2"}, "f": {"folex pfs": "2"}, "i": {"isoniazid/rifampin": "3",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "isonarif": "3",
 "isoniazid/pyrazinamide/rifampin": "3",
 "indium oxyquinoline in-111": "2"}, "m": {"methotrexate": "2",
 "morphine/naltrexone": "2",
 "methotrexate lpf sodium": "2",
 "menopause support": "2"}, "l": {"leflunomide": "3",
 "lopurin": "1"}, "n": {"naltrexone": "2",
 "neoral": "2"}, "s": {"sandimmune": "2",
 "sustiva": "2"}, "r": {"rheumatrex dose pack": "2",
 "revia": "2",
 "rebif": "2",
 "rifadin iv": "3",
 "rifater": "3",
 "rifamate": "3",
 "rifampin": "3",
 "rifadin": "3",
 "rimactane": "3"}, "t": {"tabloid": "2",
 "trexall": "2",
 "theracys": "3",
 "thioguanine": "2",
 "tice bcg vaccine": "3",
 "tice bcg": "3"}, "v": {"vivitrol": "2"}, "z": {"zyloprim": "1"}}];