interactions["ribavirin,ribapak"]=["ribavirin,ribapak", {"a": {"abacavir/lamivudine": "2",
 "azathioprine": "3",
 "abacavir": "2",
 "accesspak for hiv pep basic": "2",
 "atripla": "2",
 "accesspak for hiv pep expanded with viracept": "2",
 "abacavir/lamivudine/zidovudine": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "anisindione": "2",
 "azasan": "3"}, "c": {"coumadin": "2",
 "complera": "2",
 "combivir": "2"}, "e": {"emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "emtricitabine/rilpivirine/tenofovir": "2",
 "emtricitabine": "2",
 "epivir-hbv": "2",
 "emtricitabine/nelfinavir/tenofovir": "2",
 "emtriva": "2",
 "epivir": "2",
 "epzicom": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "emtricitabine/tenofovir": "2"}, "d": {"didanosine": "3",
 "dicumarol": "2"}, "f": {"flumist": "2"}, "i": {"influenza virus vaccine, live, trivalent": "2",
 "imuran": "3",
 "influenza virus vaccine, h1n1, live": "2"}, "h": {"hivid": "2"}, "j": {"jantoven": "2"}, "m": {"mercaptopurine": "3",
 "miradon": "2"}, "l": {"lamivudine": "2",
 "lamivudine/zidovudine": "2"}, "p": {"purinethol": "3"}, "s": {"stavudine": "2"}, "r": {"retrovir": "2"}, "t": {"truvada": "2",
 "trizivir": "2",
 "tenofovir": "2"}, "w": {"warfarin": "2"}, "v": {"videx ec": "3",
 "videx": "3",
 "viread": "2"}, "z": {"zerit": "2",
 "zalcitabine": "2",
 "ziagen": "2",
 "zerit xr": "2",
 "zidovudine": "2"}}];