interactions["sevelamer"]=["sevelamer", {"a": {"avelox": "2",
 "azithromycin/trovafloxacin": "2",
 "avelox i.v.": "2"}, "c": {"cipro xr": "2",
 "ciprofloxacin": "2",
 "cipro i.v.": "2",
 "cyclosporine": "2",
 "cinoxacin": "2",
 "cipro": "2",
 "cellcept": "2",
 "cinobac": "2",
 "cipro cystitis pack": "2"}, "e": {"enoxacin": "2",
 "euthyrox": "2",
 "evotrox": "2",
 "eltroxin": "2",
 "eutroxsig": "2"}, "g": {"grepafloxacin": "2",
 "gatifloxacin": "2",
 "gemifloxacin": "2",
 "gengraf": "2"}, "f": {"factive": "2",
 "floxin": "2",
 "floxin iv": "2"}, "m": {"maxaquin": "2",
 "myfortic": "2",
 "mycophenolic acid": "2",
 "moxifloxacin": "2",
 "mycophenolate mofetil": "2"}, "l": {"lomefloxacin": "2",
 "levo-t": "2",
 "l thyroxine roche": "2",
 "levoxyl": "2",
 "levothyrox": "2",
 "levothroid": "2",
 "levofloxacin": "2",
 "levotabs": "2",
 "levothyroxine": "2",
 "levaquin": "2",
 "levotec": "2",
 "levaquin leva-pak": "2"}, "o": {"ofloxacin": "2",
 "oroxine": "2"}, "n": {"norfloxacin": "2",
 "noroxin": "2",
 "neggram": "2",
 "neoral": "2",
 "nalidixic acid": "2"}, "p": {"prograf": "2",
 "proquin xr": "2",
 "penetrex": "2"}, "s": {"sparfloxacin": "2",
 "sandimmune": "2",
 "synthroid": "2"}, "r": {"raxar": "2"}, "u": {"unithroid": "2"}, "t": {"tequin": "2",
 "trovafloxacin": "2",
 "tequin teqpaq": "2",
 "tacrolimus": "2",
 "trovan": "2",
 "tirosint": "2"}, "z": {"zagam respipac": "2",
 "zagam": "2"}}];