interactions["silver-sulfadiazine-topical,thermazene"]=["silver-sulfadiazine-topical,thermazene", {"a": {"accuzyme se": "2",
 "accuzyme": "2",
 "allanzyme": "2",
 "allanfillenzyme": "2",
 "allanenzyme": "2"}, "c": {"collagenase topical": "2",
 "collagenase santyl": "2",
 "chlorophyllin copper complex/papain/urea topical": "2"}, "e": {"ethezyme 830": "2",
 "ethezyme 650": "2",
 "ethezyme": "2"}, "g": {"gladase": "2",
 "gladase-c": "2"}, "k": {"kovia": "2",
 "kovia 6.5": "2"}, "p": {"pap-urea": "2",
 "panafil": "2",
 "paptase": "2",
 "panafil white": "2",
 "panafil se": "2",
 "papfyll": "2",
 "papain/urea topical": "2"}, "s": {"santyl": "2"}, "z": {"ziox": "2"}}];