interactions["sodium-hyaluronate,supartz"]=["sodium-hyaluronate,supartz", {"a": {"a + d cracked skin relief": "2"}, "c": {"crest pro-health clean mint": "2",
 "cepacol anesthetic": "2",
 "cleanzing!": "2",
 "cepacol antibacterial mouthwash": "2",
 "crest pro-health cool wintergreen": "2",
 "curechrome": "2",
 "cetylpyridinium topical": "2"}, "b": {"benzalkonium chloride/pramoxine topical": "2",
 "benza": "2",
 "benzalkonium chloride/benzocaine topical": "2",
 "benzocaine/cetylpyridinium topical": "2",
 "benzalkonium chloride topical": "2",
 "benzalkonium chloride/lidocaine topical": "2",
 "benzalkonium chloride/menthol topical": "2"}, "d": {"dr scholl's cracked heel relief": "2"}, "f": {"first aid antiseptic": "2"}, "h": {"herpetrol": "2"}, "m": {"mercuroclear": "2"}, "o": {"orajel mouth-aid liquid": "2",
 "orajel anti-bacterial bleeding gum rinse": "2",
 "orajel mouth sore medicine gel": "2",
 "oral-b rinse": "2"}, "n": {"neosporin neo to go!": "2"}, "p": {"protac": "2",
 "pedi-pro": "2"}, "t": {"tanac": "2"}, "z": {"zephiran chloride": "2"}}];