interactions["varenicline"]=["varenicline", {"c": {"commit": "2",
 "cimetidine": "1"}, "e": {"equaline acid reducer": "1"}, "h": {"habitrol": "2"}, "l": {"lamictal xr": "1",
 "lamictal cd": "1",
 "lamictal": "1",
 "lamictal odt": "1",
 "lamotrigine": "1",
 "leader nicotine polacrilex": "2"}, "n": {"nicotine": "2",
 "nicoderm cq": "2",
 "nicotrol ns": "2",
 "nicorette": "2",
 "nicotrol inhaler": "2",
 "nicorelief": "2",
 "nicotrol td": "2",
 "nicorette ds": "2"}, "p": {"prostep": "2"}, "t": {"tagamet hb": "1",
 "tagamet": "1"}}];