interactions["xylometazoline-nasal,otrivin"]=["xylometazoline-nasal,otrivin", {"a": {"atapryl": "2",
 "azilect": "2"}, "c": {"cymbalta": "2",
 "carbex": "2"}, "e": {"effexor": "2",
 "eldepryl": "2",
 "emsam": "2",
 "effexor xr": "2"}, "d": {"desvenlafaxine": "2",
 "duloxetine": "2"}, "f": {"furazolidone": "2",
 "furoxone": "2"}, "i": {"isocarboxazid": "2"}, "j": {"jumex": "2"}, "m": {"milnacipran": "2",
 "meridia": "2",
 "matulane": "2",
 "marplan": "2"}, "l": {"linezolid": "2"}, "n": {"nardil": "2",
 "nucynta": "2",
 "nucynta er": "2"}, "p": {"parnate": "2",
 "phenelzine": "2",
 "procarbazine": "2",
 "pristiq": "2"}, "s": {"selgene": "2",
 "selegiline": "2",
 "savella": "2",
 "sibutramine": "2"}, "r": {"rasagiline": "2"}, "t": {"tapentadol": "2",
 "tranylcypromine": "2"}, "v": {"venlafaxine": "2"}, "z": {"zelapar": "2",
 "zyvox": "2"}}];